volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped 

  backend:
    image: olgatimofeeva/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: olgatimofeeva/kittygram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: olgatimofeeva/kittygram_gateway:latest
    env_file: .env 
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
    restart: unless-stopped 
